### ISSUE TITLE
Local webserver for OBS overlay

### ISSUE THREAD

**Issue by Dthen** [jukibom/FlyDangerous#100]
It would add greatly to Fly Dangerous for there to be built-in support for stream overlays via OBS. Usually, these are added to OBS as a web source, so a local webserver would likely be the easiest thing for users.

Some desired/ ideas for info to display:

- inputs
- speed
- lap/position counters
- current map name
- split times

What else?

**Comment by nova-triio** [comment]
Leaderboard Widget? 
Minimap (sounds crazy, but surely its just one extra viewpoint above you?)
Personal Best (when not already shown)
G Meter (When in Puffin)
Boost display (when in Puffin)

So many ideas!

**Comment by Tallefer** [comment]
I have no idea whether it should be a different issue or this one, but:
A similar mode/server/api/whatever for the (headless) game server. The same thing as in "Pro" competitive games - a global overhead view and a table/popups with enough info on all players and handy camera controls for streaming commentators

**Comment by Dthen** [comment]
> I have no idea whether it should be a different issue or this one, but: A similar mode/server/api/whatever for the (headless) game server. The same thing as in "Pro" competitive games - a global overhead view and a table/popups with enough info on all players and handy camera controls for streaming commentators

Like a really good spectator mode?

**Comment by Tallefer** [comment]
You can call it that, yes. It kinda blends together with the spectator mode, but the notable difference is that a "normal" client should not have all the information a dedicated server has, be it for performance reasons or/and as an anti-cheat measure.

**Comment by Dthen** [comment]
Right, got ya. The line is a bit blurred. Arguably, a good enough spectator mode shouldn't need an overlay. I picture the overlay being more useful for pilots who are broadcasting their gameplay.

Another thought. Not sure whether it makes sense for the server to be highly configurable, or for it to just have multiple widgets/pages.

**Comment by bekopharm** [comment]
As a [simPit](https://en.wikipedia.org/wiki/Simulation_cockpit) player I'm also highly interested in such data. IPC or Websocket would be highly appreciated so custom UI elements can be programmed. A low latency is key here. 

Not so much interested in inputs. There are plenty of overlay solutions for input already.

**Comment by jukibom** [comment]
JSON data available in 0.6.0, https://github.com/jukibom/FlyDangerous/blob/main/Assets/Scripts/Core/ShipModel/Feedback/socket/FlyDangerousTelemetry.cs
