### ISSUE TITLE
Mac OS build (Specifically for M1 Mac)

### ISSUE THREAD

**Issue by CMDR-Piboy314** [jukibom/FlyDangerous#102]
Hello! I recently got a brand new M1 Mac and was installing games. At the same time my friend and Elite Dangerous Fanboy installed Fly Dangerous on Windows and asked me to also. I was disappointed when I saw no Mac build on itch.io, if a mac build could be added that'd be awesome! Thank you and o7 CMDRs! 👾 🛰️

**Comment by jukibom** [comment]
@CMDR-Piboy314 added a mac (intel / M1) build to https://github.com/jukibom/FlyDangerous/releases/tag/v0.4.1 

You may need to manually set the unix file permissions on the folder (open terminal and run `sudo chmod -R 755 flydangerous.app` in whatever folder you run it from. Beyond that I'm flying blind so let me know how you get on

**Comment by CMDR-Piboy314** [comment]
Thank you very much @jukibom! It works after manually setting the unix file permissions with the command you attached!

**Comment by jukibom** [comment]
Excellent, I may be able to set those permissions manually with WSL before packaging next time. I'll try that with the next release and add instructions for now.

**Comment by CMDR-Piboy314** [comment]
Sorry, I just tested the game and it's frozen at LOADING Generating terrain (0%)

<img width="1440" alt="Screen Shot 2021-10-04 at 7 49 06 PM" src="https://user-images.githubusercontent.com/91815910/135838734-7ab90600-5d9c-4c66-8517-dcab671f0b02.png">

Though after further testing it seems like some things work… sometimes…

<img width="1440" alt="Screen Shot 2021-10-04 at 7 58 40 PM" src="https://user-images.githubusercontent.com/91815910/135840649-5a6be9b2-bcd6-4335-a9de-909593d007c7.png">

Free Roam does NOT work, and time trial only seems to work after going to settings and clicking apply then trying again...

This is a very strange & confusing issue, if you have anything you'd like me to try please let me know.

**Comment by jukibom** [comment]
Sounds like terrain gen is broken like Linux :(

**Comment by CMDR-Piboy314** [comment]
Yeah the terrain gen screen is the screen of death :(
