### ISSUE TITLE
Helpers for Lutris installer

### ISSUE THREAD

**Issue by mioux** [jukibom/FlyDangerous#144]
I wrote an installer for the game in [lutris](https://lutris.net/games/fly-dangerous/)

2 things could make it easier :
- Make a tar.gz file instead of a zip, with fly_dangerous.x86_64 set to executable (to remove the chmodx directive)
- Having a static link that redirects to the latest build release (to avoid updating the installer script for each new release)

FYI, here is the installer script

    files:
    - gh_zip: https://github.com/jukibom/FlyDangerous/releases/download/v0.5.4/FlyDangerous-0.5.4-linux.zip
    game:
      exe: flydangerous.x86_64
    installer:
    - extract:
        dst: $GAMEDIR
        src: gh_zip
    - chmodx: $GAMEDIR/flydangerous.x86_64

**Comment by mioux** [comment]
The executable bit is not the worst thing, as there is a command for Lutris to dot that 😄 

But if you remove the version text in the file (at least for the Linux version), then I can use the link you provided (I don't knew you can put "latest" as release 👍 )

After next release, I'll update the installer script, so it will always download the latest version

**Comment by jukibom** [comment]
@mioux I didn't forget about this! The new version goes up today (in about 6 hours, roughly) BUT it's too large for the max github filesize so there's two files

`fly-dangerous-linux.tar.gz.001`
`fly-dangerous-linux.tar.gz.002`

I hope that'll still work...

**Comment by mioux** [comment]
I have changed the installer. It will work until there is a third file to download :smile: 

It's not visible for now as it has to be submitted for aproval before public release

Thank you
