### ISSUE TITLE
Screen shake bug

### ISSUE THREAD

**Issue by jukibom** [jukibom/FlyDangerous#145]
A user has filed a report that the camera can get into uncontrollable shaking, "by changing the control mode from Advanced to Arcade while being loaded into a time trial". Not quite sure what this one is about but could do with further investigation...

**Comment by Timbraska** [comment]
Yep this is the video to the bug https://www.dropbox.com/s/xfr4wa4vw3b06de/Shakebug.mp4?dl=0 I muted the audio, because I was talking with a friend while playing if you insist I can also upload it with sound but I doubt that this makes a difference

**Comment by Timbraska** [comment]
It is on windows. I don't know exactly when it happens since I tried to trigger it again but this time it didn't occur. But in total this bug occured to me 3-4 times, whenever I was in timetrial and trying to adjust the controls to my liking.

**Comment by jukibom** [comment]
@Timbraska I *think* this was related to string encoding and may be fixed with the most recent patch on steam - could you confirm?

**Comment by Timbraska** [comment]
I had 2 clips saved which produced the bug and I exactly repeated both of them without triggering the bug. So I think the bug is gone.
