### ISSUE TITLE
Possible discrepency between HMD recenter in the menu and in-game

### ISSUE THREAD

**Issue by jukibom** [jukibom/FlyDangerous#146]
Seen too many people now with the VR camera directly above the ship for it to be some arbitrary VR-space offset. Suspect F11 in the main menu is different to in-game? 

If not, two solutions do present themselves:
- [x] If a calibration isn't detected in the save file, show a VR-specific pop-up in VR mode on the menu explaining the Recenter binding
- [x] At the same time, If a calibration isn't detected in the save file, perform an automatic calibration at startup (most users will have the headset on or near their head on startup)

**Comment by alterNERDtive** [comment]
Adding it to the arcade mode controls overview should help with people not knowing what to do as well.

Currently the only way to find it in the bindings is to switch to advanced mode and look at the list.

Side question, I’m assuming that arcade mode will hard default it back to F11 even if something else is configured in advanced mode?

**Comment by jukibom** [comment]
> Side question, I’m assuming that arcade mode will hard default it back to F11 even if something else is configured in advanced mode?

Hmmmm actually no, and that's a very good point. HMD reset lives in a global action set and the rebind for it will modify that globally. 

I also recently moved the restart key into there to allow it to work in the end panel - I may need to have two separate global action sets 🤦‍♀️
