### ISSUE TITLE
Add a fps cap option

### ISSUE THREAD

**Issue by jukibom** [jukibom/FlyDangerous#170]
I never understood this but some people want it

**Comment by Dthen** [comment]
I think the idea is that if it's left uncapped and the GPU is capable of rendering far more frames than necessary, oftentimes more frames per second than the monitor can display, to cap the FPS and any work the GPU is doing beyond that is "wasted".

**Comment by xenago** [comment]
@Dthen is correct. It can also help keep the framerate within the GSync/VRR window, and (counterintuitively) reduce latency in some situations.
