### ISSUE TITLE
Flight vector drawing (for debug and possible indicator display, eventually collision prediction for the user)

### ISSUE THREAD

**Issue by jukibom** [jukibom/FlyDangerous#18]
(Actually is this even needed now that space dust is in?)

**Comment by jukibom** [comment]
Related to #115

**Comment by Jamma003** [comment]
Example of 3d navball from Kerbal Space Program
![image](https://user-images.githubusercontent.com/17299012/169083115-d46f284b-f8f5-4fec-a09f-91d09cefc474.png)
