### ISSUE TITLE
bHaptics support

### ISSUE THREAD

**Issue by jukibom** [jukibom/FlyDangerous#194]
Add support for bHaptics for the following events

- [x] Boost started
- [x] Boost active
- [x] Collisions
- [x] Ship Shake
- [x] Ship function
- [x] limiter active

Ideally abstract through some sort of feedback interface for future use

I think anything else that should trigger haptics (e.g. engine usage over, say, 80%) should also cause the ship to shake and therefore follow through to haptics.

If anyone has any more I'm happy to look at it

Related (kinda) to  #115

**Comment by Codebreakerblue** [comment]
Could add a low-intensity pattern while the speed limiter is active, and/or small blips when toggling flight assists and lights

**Comment by jukibom** [comment]
Ohhh those are really good ideas!
