### ISSUE TITLE
Hard crash on Linux PC [public_beta]

### ISSUE THREAD

**Issue by bekopharm** [jukibom/FlyDangerous#210]
Played fine for some minutes before crashing back to desk hard. This happened several times. 

```
	0x7fa451b15126 - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/flydangerous_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so : 
	0x7fa451abde02 - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/flydangerous_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so : 
	0x7fa451a43280 - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/flydangerous_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so : 
	0x7fa51cc3ea30 - /lib64/libc.so.6 : 
	0x7fa51cd5806b - /lib64/libc.so.6 : 
	0x7fa51df079fd - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/UnityPlayer.so : 
	0x7fa51e60ca5d - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/UnityPlayer.so : 
	0x7fa51e60e0fd - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/UnityPlayer.so : 
	0x7fa51e60980f - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/UnityPlayer.so : 
	0x7fa51e609535 - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/UnityPlayer.so : 
	0x7fa51dd26379 - /data/beko/.local/share/Steam/steamapps/common/Fly Dangerous/UnityPlayer.so : 
	0x7fa51cc8cded - /lib64/libc.so.6 : 
	0x7fa51cd12370 - /lib64/libc.so.6 : 
```

Here is a mini dmp and the Player log (no idea if this is of any use):

[assert_20230208193352_3.zip](https://github.com/jukibom/FlyDangerous/files/10688920/assert_20230208193352_3.zip)

**Comment by jukibom** [comment]
`[bhaptics] BhapticsManager.cs - GetHaptic() / haptic_library assembly:<unknown assembly> type:<unknown type> member:(null)`

Ah, looks like bhaptics doesn't support linux 😵‍💫 I'll need to make this windows-only, most likely. Does this still occur if disabling bhaptics in the integrations tab? (I should prolly make this off by default in any case!)

**Comment by bekopharm** [comment]
Needs a more recent Linux native build :upside_down_face: 

Worked fine via Proton on a more recent build.
