### ISSUE TITLE
Look around binding

### ISSUE THREAD

**Issue by jukibom** [jukibom/FlyDangerous#57]
Mouse look (instead of mouse control) or binding to an axis

**Comment by nova-triio** [comment]
Would be nice to put this on a toggle between look and input, and a stick axis. EG on a controller, you press in a stick and it switches, say, your right stick from ship control to headlook... That's how it is in elite, and it works very well for limited numbers of input buttons. 🚀

**Comment by jukibom** [comment]
@nova-triio useful, thank you! I can't remember the last time I used it in elite as I only play it with VR

**Comment by jukibom** [comment]
@nova-triio unfortunately it's too much work to get that to work in a generic way (because anything could be bound to anything!) but I've added a toggle to enable or disable the camera look system which, if combined with alternate flight controls (bind the same action to toggle alt flight and move camera) you can achieve the same effect with a little work.
