### ISSUE TITLE
Loading screen reset bug

### ISSUE THREAD

**Issue by nova-triio** [jukibom/FlyDangerous#64]
when loading a fresh seed from start menu, spam reset, and boost, a second loading screen may pop up, and a bunch of elements dont load, after about 20 seconds a few elements spawn, all else is left empty, or not there at all. Ground and terrain hitboxes also disappear, ive only replicated it 3 times, but it is quite easy to do, at least on my client.

-nova.

**Comment by jukibom** [comment]
fixed (I think?) in 0.3.0 (reopen if you can repro it!)
