### ISSUE TITLE
Spectator mode in multiplayer

### ISSUE THREAD

**Issue by jukibom** [jukibom/FlyDangerous#68]
The ability to leave the game and spectate other players in the pilot seat.

**Comment by nova-triio** [comment]
maybe allow the pilot to pass over control to the copilot, and the pilot can override and take it back... ideas!

**Comment by jukibom** [comment]
oooo like a training mode, interesting.

**Comment by jukibom** [comment]
literally how did I miss this freaking thing when searching for an existing issue
