### ISSUE TITLE
Scroll speed on menus is slow

### ISSUE THREAD

**Issue by minus1over12** [jukibom/FlyDangerous#72]
Scrolling a page takes a long time.
Video: https://youtu.be/Kk-jSrq_CnI
I'm running on Linux, which might be part of the issue.

**Comment by Lignar** [comment]
Yeah, I can confirm and it's indeed Linux-specific issue. Also, scroll is actually inverted.

**Comment by jukibom** [comment]
Wow that's not slow that's _glacial_! I'll see what I can do
