### ISSUE TITLE
Space Station Missing Collisions

### ISSUE THREAD

**Issue by minus1over12** [jukibom/FlyDangerous#73]
The space station is missing collision in a few points.
Video demo: https://youtu.be/3y5OalClxNg

**Comment by jukibom** [comment]
Yep I was pretty sloppy with it to be honest, and the scene will likely get removed in favour of something higher quality reasonably soon as it was just a test case.

**Comment by jukibom** [comment]
fixed in 0.3.0

**Comment by minus1over12** [comment]
The collisions shown at 0:56 and 1:38 aren't fixed in 0.3.0

For the one at 0:56, you're aiming for a little cut on the texture to go through. My cursor is aimed at it in this screenshot, you can see it if you zoom in a bit.
![split](https://user-images.githubusercontent.com/54217755/129430443-3bb89a05-8c01-41ba-aef1-9df54fc55fb3.png)
