### ISSUE TITLE
Terrain generation loading stuck when creating freeroam game

### ISSUE THREAD

**Issue by Meister1593** [jukibom/FlyDangerous#85]
When running singleplayer game with time trial, it works fine and launches good, but when launching freeroam game with any seed and default style (Sunrise, Clear) it stops on generating terrain and does it infinitely, and game never launches.
Linux native game.
Tried running with Steam Linux Runtime too (i thought maybe it's a bug with fresh libraries), didn't work either
System: Arch Linux, 5.13-9 kernel
Specs: cpu - Ryzen 1600, gpu - XFX RX 480 (mesa 21.1.6-1)

**Comment by Soaku** [comment]
The issue was resolved earlier and it's most likely just a faulty build. Can reproduce.

Hijacking the issue though, it might be a good idea to add a "cancel" button to the loading screen.

**Comment by Meister1593** [comment]
> The issue was resolved earlier and it's most likely just a faulty build. Can reproduce.
> 
> Hijacking the issue though, it might be a good idea to add a "cancel" button to the loading screen.

Good idea, like "Go back to main menu"  after 30 seconds of loading

**Comment by jukibom** [comment]
should be fixed in 0.4.0
